module.exports = {
  path: 'analysis/GWASUIApp',

  // Xpath:
  CaseControlTitle: '//div[contains(text(),"Case Control GWAS")]',
  CaseControlInput: '(//input[@class="ant-checkbox-input"])[1]',
  QuantitativeInput: '(//input[@class="ant-checkbox-input"])[2]',
  SelectCohortTitle: '//th[contains(text(),"Cohort Name")]',
  SelectFirstRadioInput: '(//input[@class="ant-radio-input" and not(@disabled)])[1]',
  SelectConceptTitle: '//th[contains(text(),"Concept ID")]',
  SelectFirstCheckboxInput: '(//input[@class="ant-checkbox-input"])[1]',
  SelectSecondCheckboxInput: '(//input[@class="ant-checkbox-input"])[2]',
  SelectGroupsButton: '//button[@label="Dropdown Button" and contains(text(),"ancestry")]',
  SelectGrupsDropdown: '(//div[@class=" g3-dropdown__item "])[1]',
  EnterJobName: '//input[@class="GWASUI-nameInput"]',
  SelectPhenotypeTitle: '//th[contains(text(),"Phenotype")]',
  SetParameterDiv: '//*[@class="GWASUI-mainArea"]',
  NextSpan: '//span[contains(text(),\'Next\')]',
  PreviousSpan: '//span[contains(text(),\'Previous\')]',
  SubmitButton: '//span[contains(text(),\'Submit\')]',
  JobStatusesButton: '//*[contains(text(),"Statuses")]',
  JobIDs: '//h4[contains(text(),"Run ID")]',
  JobComplete: '//span[contains(text(),"Completed")]',
  JobInProgress: '//span[contains(text(),"Progress")]',
  JobCanceling: '//span[contains(text(),"Cancelling")]',
  JobStarted: '//div[contains(text(),"Started at")]',
  JobFinished: '//div[contains(text(),"finished at")]',
  JobDeleteButton: '//span[contains(text(),"delete")]',
  JobDeletePopup: '//div[contains(text(),"Are you sure")]',
  JobDeleteYes: '//span[contains(text(),"Yes")]',
  JobDeleteNo: '//span[contains(text(),"No")]',
  DownloadOutputButton: '//span[contains(text(),"download")]',
};
