module.exports = {
  path: 'analysis/GWASUIApp',

  // Xpath:
  AppsNavigationTab: '//a[contains(text(),"Apps")]',
  GWASResultTitle: '//h2[contains(text(),"GWAS Results")]',
  CaseControlTitle: '//div[contains(text(),"Case Control GWAS")]',
  CaseControlInput: '(//input[@class="ant-checkbox-input"])[1]',
  QuantitativeTitle: '//div[contains(text(),"Quantitative Phenotype")]',
  QuantitativeInput: '(//input[@class="ant-checkbox-input"])[2]',
  SelectCohortTitle: '//th[contains(text(),"Cohort Name")]',
  SelectFirstRadioInput: '(//input[@class="ant-radio-input" and not(@disabled)])[1]',
  SelectSecondRadioInput: '(//input[@class="ant-radio-input" and not(@disabled)])[2]',
  SelectedRadio: '(//*[@class="ant-radio ant-radio-checked"])',
  SelectConceptTitle: '//th[contains(text(),"Concept ID")]',
  SelectFirstCheckboxInput: '(//input[@class="ant-checkbox-input"])[1]',
  SelectSecondCheckboxInput: '(//input[@class="ant-checkbox-input"])[2]',
  SelectGroupsButton: '//button[@label="Dropdown Button" and contains(text(),"ancestry")]',
  SelectGrupsDropdown: '(//div[@class=" g3-dropdown__item "])[1]',
  EnterJobName: '//input[@class="GWASUI-nameInput"]',
  SelectPhenotypeTitle: '//th[contains(text(),"Phenotype")]',
  SetParameterDiv: '//*[@class="GWASUI-mainArea"]',
  NextSpan: '//span[contains(text(),\'Next\')]',
  PreviousSpan: '//span[contains(text(),\'Previous\')]',
  SubmitButton: '//span[text()="Submit"]',
  JobStatusesButton: '//*[contains(text(),"Statuses")]',
  JobIDs: '//h4[contains(text(),"Run ID")]',
  JobComplete: '//span[contains(text(),"Completed")]',
  JobInProgress: '//span[contains(text(),"Progress")]',
  JobCanceling: '//span[contains(text(),"Cancelling")]',
  JobStarted: '//div[contains(text(),"Started at")]',
  JobFinished: '//div[contains(text(),"finished at")]',
  SelectDifferentType: '//span[contains(text(),"Select Different GWAS Type")]',
  AreyousurePopup: '//div[contains(text(),"Are you sure")]',
  AreyousureYes: '//span[contains(text(),"Yes")]',
  AreyousureNo: '//span[contains(text(),"No")]',
  DownloadOutputButton: '//span[contains(text(),"download")]',
  CohortSearchBar: '//div[@class="GWASUI-searchContainer"]',
  CohortSearchResult: '//td[contains(text(),"medium")]',
  ConceptSearchBar: '//input[@class="GWASUI-searchInput"]',
  ConceptSearchResult: '//td[contains(text(),"Attribute10")]',
  CohortSearchBar1: '(//input[@class="GWASUI-searchInput"])[1]',
  CohortSearchResult1: '//td[contains(text(),"Large")]',
  CohortSearchBar2: '(//input[@class="GWASUI-searchInput"])[2]',
  CohortSearchResult2: '//td[contains(text(),"medium")]',
};
